// Mock data for the Bike News Room prototype.
// Article shape mirrors the backend contract from the brief.

const SOURCES = [
  { id: "cyclingnews", name: "CyclingNews", country: "gb" },
  { id: "pinkbike", name: "Pinkbike", country: "ca" },
  { id: "velo", name: "Velo", country: "us" },
  { id: "rouleur", name: "Rouleur", country: "gb" },
  { id: "bikeradar", name: "BikeRadar", country: "gb" },
  { id: "naszosie", name: "NaSzosie", country: "pl" },
  { id: "ciclismo21", name: "Ciclismo21", country: "es" },
  { id: "marca", name: "Marca Ciclismo", country: "es" },
  { id: "vitalmtb", name: "Vital MTB", country: "us" },
  { id: "uci", name: "UCI Press", country: "ch" },
];

const DISCIPLINES = [
  { id: "road", label: "Road", hue: 245 },
  { id: "mtb", label: "MTB", hue: 145 },
  { id: "gravel", label: "Gravel", hue: 60 },
  { id: "track", label: "Track", hue: 295 },
  { id: "cx", label: "CX", hue: 15 },
  { id: "bmx", label: "BMX", hue: 330 },
];

const REGIONS = [
  { id: "world", label: "World", flag: "🌍" },
  { id: "eu", label: "EU", flag: "🇪🇺" },
  { id: "poland", label: "Poland", flag: "🇵🇱" },
  { id: "spain", label: "Spain", flag: "🇪🇸" },
];

const CATEGORIES = [
  { id: "results", label: "Results" },
  { id: "transfers", label: "Transfers" },
  { id: "equipment", label: "Equipment" },
  { id: "events", label: "Events" },
  { id: "general", label: "General" },
];

// Minutes-ago helper for reproducibility
const NOW = new Date("2026-05-01T14:30:00Z").getTime();
const ago = (mins) => new Date(NOW - mins * 60000).toISOString();

const ARTICLES = [
  {
    id: 91,
    title: "Berwick seizes Tour of Turkey lead with daring stage 6 attack on Antalya climb",
    description: "The 24-year-old Australian overhauled previous race leader Sebastián Molano with a long-range solo move on the Tahtalı ascent, taking second on the stage and the overall lead by 14 seconds heading into the queen stage.",
    url: "https://www.cyclingnews.com/news/berwick-tour-turkey",
    image_seed: "1",
    published_at: ago(18),
    category: "results",
    region: "world",
    discipline: "road",
    language: "en",
    source: "cyclingnews",
    cluster: ["velo", "rouleur", "marca"],
    isLive: true,
  },
  {
    id: 92,
    title: "Vingegaard signs three-year extension with Visma at reported €5M per season",
    description: "The two-time Tour de France champion commits his future to the Dutch squad through 2029, ending months of speculation about a possible move to UAE Team Emirates.",
    url: "https://www.rouleur.cc/vingegaard-extension",
    image_seed: "2",
    published_at: ago(42),
    category: "transfers",
    region: "eu",
    discipline: "road",
    language: "en",
    source: "rouleur",
    cluster: ["cyclingnews", "velo"],
  },
  {
    id: 93,
    title: "Pidcock takes Andorra World Cup XCO win in muddy conditions",
    description: "Returning to MTB after his road campaign, the Brit dominates a sodden technical course, distancing Schurter and Avancini on the third lap.",
    url: "https://www.pinkbike.com/news/pidcock-andorra",
    image_seed: "3",
    published_at: ago(67),
    category: "results",
    region: "eu",
    discipline: "mtb",
    language: "en",
    source: "pinkbike",
    cluster: ["vitalmtb"],
  },
  {
    id: 94,
    title: "First ride: Specialized's new Crux DSW gravel race bike",
    description: "Aluminium frame, carbon fork, 1,180g claimed weight. The DSW promises Crux geometry at half the price — we put 200km on it across the Girona backroads.",
    url: "https://www.bikeradar.com/reviews/crux-dsw",
    image_seed: "4",
    published_at: ago(95),
    category: "equipment",
    region: "world",
    discipline: "gravel",
    language: "en",
    source: "bikeradar",
  },
  {
    id: 95,
    title: "Kwiatkowski potwierdza start w Wyścigu Solidarności",
    description: "Polski mistrz świata z 2014 roku wraca na rodzime drogi po pięcioletniej przerwie, prowadząc skład INEOS Grenadiers w lipcowym wyścigu.",
    url: "https://www.naszosie.pl/kwiatkowski-solidarnosci",
    image_seed: "5",
    published_at: ago(120),
    category: "events",
    region: "poland",
    discipline: "road",
    language: "pl",
    source: "naszosie",
  },
  {
    id: 96,
    title: "Track Worlds 2026: Lavreysen completes sprint treble in Santiago",
    description: "The Dutch sprinter wins keirin, sprint, and team sprint titles for the fifth consecutive year, cementing his case as the greatest track sprinter of all time.",
    url: "https://www.uci.org/track-worlds-2026",
    image_seed: "6",
    published_at: ago(145),
    category: "results",
    region: "world",
    discipline: "track",
    language: "en",
    source: "uci",
    cluster: ["cyclingnews"],
  },
  {
    id: 97,
    title: "Van der Poel teases cyclocross return at Koksijde in December",
    description: "The world champion hints at a partial CX campaign, citing 'unfinished business' with Wout van Aert as motivation for the muddy comeback.",
    url: "https://www.velo.com/mvdp-cx-return",
    image_seed: "7",
    published_at: ago(180),
    category: "general",
    region: "eu",
    discipline: "cx",
    language: "en",
    source: "velo",
  },
  {
    id: 98,
    title: "Vuelta a España route revealed: three summit finishes in final week",
    description: "Organisers unveil a 3,278km parcours with the queen stage to Anglirú on day 19, plus a return to Lagos de Covadonga and a new finish on Picón Blanco.",
    url: "https://www.marca.com/vuelta-2026-recorrido",
    image_seed: "8",
    published_at: ago(210),
    category: "events",
    region: "spain",
    discipline: "road",
    language: "es",
    source: "marca",
    cluster: ["cyclingnews", "rouleur", "velo"],
  },
  {
    id: 99,
    title: "Why pro riders are switching to 165mm cranks in 2026",
    description: "Shorter cranks, once a TT-only choice, are now standard on road bikes from WorldTour to junior level. The biomechanics behind the trend.",
    url: "https://www.bikeradar.com/cranks-165",
    image_seed: "9",
    published_at: ago(260),
    category: "equipment",
    region: "world",
    discipline: "road",
    language: "en",
    source: "bikeradar",
  },
  {
    id: 100,
    title: "Ferrand-Prévot announces road program with Visma–Lease a Bike",
    description: "The Olympic XCO champion will target the Tour de France Femmes and Paris–Roubaix in her first full road season, while keeping a reduced MTB schedule.",
    url: "https://www.cyclingnews.com/pfp-road-program",
    image_seed: "10",
    published_at: ago(310),
    category: "transfers",
    region: "world",
    discipline: "road",
    language: "en",
    source: "cyclingnews",
  },
  {
    id: 101,
    title: "BMX: Worthington takes World Cup overall with Manchester win",
    description: "The Brit closes out the season with a third round victory, beating Niek Kimmann in a tight final to seal the overall title.",
    url: "https://www.cyclingnews.com/worthington-bmx",
    image_seed: "11",
    published_at: ago(380),
    category: "results",
    region: "world",
    discipline: "bmx",
    language: "en",
    source: "cyclingnews",
  },
  {
    id: 102,
    title: "Movistar fichará a un joven escalador colombiano para 2027",
    description: "El equipo español ultima la firma de un escalador de 22 años actualmente en un equipo continental, según fuentes próximas a la operación.",
    url: "https://www.ciclismo21.com/movistar-fichaje",
    image_seed: "12",
    published_at: ago(420),
    category: "transfers",
    region: "spain",
    discipline: "road",
    language: "es",
    source: "ciclismo21",
  },
  {
    id: 103,
    title: "Unbound Gravel 2026 registration opens — lottery returns",
    description: "Entry for the 200-mile flagship event opens November 1. Organisers confirm a return to the lottery system after last year's first-come-first-served chaos.",
    url: "https://www.velo.com/unbound-2026",
    image_seed: "13",
    published_at: ago(540),
    category: "events",
    region: "world",
    discipline: "gravel",
    language: "en",
    source: "velo",
  },
  {
    id: 104,
    title: "Loïc Bruni: 'I'm not done yet' — Frenchman targets sixth DH world title",
    description: "Five-time downhill world champion talks training, motivation, and the new generation of Vali Höll and Jackson Goldstone breathing down his neck.",
    url: "https://www.pinkbike.com/bruni-interview",
    image_seed: "14",
    published_at: ago(620),
    category: "general",
    region: "eu",
    discipline: "mtb",
    language: "en",
    source: "pinkbike",
  },
  {
    id: 105,
    title: "Live race ticker: Stage 6 Tour of Turkey",
    description: "Updating live as Berwick's solo move grows. 12km to go.",
    url: "#",
    image_seed: "15",
    published_at: ago(8),
    category: "results",
    region: "world",
    discipline: "road",
    language: "en",
    source: "cyclingnews",
    isLive: true,
  },
];

// Live race state, used by the LIVE banner
const LIVE_RACE = {
  name: "Tour of Turkey",
  stage: "Stage 6",
  stageDetail: "Antalya → Kemer · 184 km",
  km_done: 172,
  km_total: 184,
  leader: { name: "S. Berwick", team: "Jayco AlUla", gap: "solo" },
  chasers: [
    { name: "S. Molano", team: "UAE Emirates", gap: "+0:42" },
    { name: "B. Healy", team: "EF Education", gap: "+0:42" },
    { name: "Peloton", team: "—", gap: "+1:18" },
  ],
};

// Suggested searches for the search overlay
const SUGGESTED = [
  "Pogačar",
  "Vingegaard",
  "Vuelta",
  "Pinarello Dogma",
  "Pidcock",
  "Worlds 2026",
  "Roubaix",
  "Van der Poel",
];

const RECENT_SEARCHES = ["pogacar", "tour of turkey", "specialized crux"];

// Bookmark seed
const SEED_BOOKMARKS = [92, 94, 98];

window.BNR_DATA = {
  SOURCES,
  DISCIPLINES,
  REGIONS,
  CATEGORIES,
  ARTICLES,
  LIVE_RACE,
  SUGGESTED,
  RECENT_SEARCHES,
  SEED_BOOKMARKS,
  NOW,
};
